---
title: "Time Series Analysis: Modelling the Periodic Component of Monthly Data using Fourier Series Harmonic Analysis in RStudio"
author: ORVILLE D. HOMBREBUENO
output: 
    html_notebook
documentclass: article
csl: apa.csl
bibliography: FSHA_vignette.bib
nocite: '@*'
---

In this vignette, I will be showing basic Fourier series harmonic analysis [@weltner14]. I will show how to fit a Fourier series model to the periodic component of monthly rainfall data using R [@R] in RStudio[@RStudio]. Doing this, I will be following the model-building steps spoused by @box16: 1. model specification, 2. model fitting, 3. model diagnostics.

In this vignette, I will be discussing the basics of time series analysis in the frequency domain. I will focus on the use of Fourier series harmonic analysis to model the periodic component of monthly data. I will first discuss some basic concepts in time series analysis and then continue discussing Fourier series harmonic analysis and its application to modelling the periodic component of monthly data. To provide an example, Fourier series harmonic analysis will be applied to monthly rainfall data using RStudio [@RStudio]. This vignette attempts to provide basic concepts of  model fitting that will serve as stepping stones to advanced Fourier analysis of time series data.

# Time Series Analysis

Time series data comes in many forms. It can be yearly, quarterly, monthly, daily and even hourly data. It can be heart rates at a given interval, it can be daily stock closing and opening prices, it can be hourly precipitation and temperature, it can be yearly population, etc. It's not a surprise, in the 4th industrial revolution, time series data is available in almost all fields. Time series analysis is performed to gain insights -- periodic and trend behavior -- that will serve as basis for decision making. Imagine if farmers know the periodic behavior of rainfall. They will know what to plant, and when to plant it. Imagine if heavy rainfall can be predicted, disasters caused by floods can be minimized. Time series analysis can be very powerful and useful.

The main features of many time series are trends and seasonal variations
that can be modelled deterministically with mathematical functions of
time.

Time series analysis is usuallycan be done in the time domain or frequency domain.




A given time series with respect to time $y(t)$ can be decomposed into the sum of its periodic component $P_{t}$, its trend component $T_{t}$, and random component $\epsilon_{t}$:

\begin{equation}
y(t)=P_{t}+T_{t}+\epsilon_{t}.
\end{equation}

```{r}
load("~/R/R Projects/Rain Project/fmsmTS/Data/fmsmrdata1215.RData")
plot(decompose(fmsmrdata1215))
```


Fourier series is very appropriate to model 

# Fourier Series

\begin{equation}
f(x)=\frac{a_{0}}{2}+\sum_{n=1}^{\infty} a_{n} \cos n x+\sum_{n=1}^{\infty} b_{n} \sin n x
\end{equation}

\begin{equation}
\begin{aligned}
&a_{0}=\frac{1}{\pi} \int_{-\pi}^{\pi} f(x) \mathrm{d} x\\
&a_{n}=\frac{1}{\pi} \int_{-\pi}^{\pi} f(x) \cos n x \mathrm{d} x \quad n=1,2, \ldots\\
&b_{n}=\frac{1}{\pi} \int_{-\pi}^{\pi} f(x) \sin n x \mathrm{d} x \quad n=1,2, \ldots
\end{aligned}
\end{equation}

# Fourier Series Harmonic Analysis

A function $f(x)$ of period $2L$ is repeated when $x$ increases by $2L$, i.e.

\begin{equation}
f(x+2L)=f(x)
\end{equation}

If we put $z=\frac{\pi}{L} x$, then the new function $f(z)$ is a periodic function of period $2\pi$. As $x$ increases from $-L$ to $L$, $z$ increases from $-\pi$ to $\pi$. We have

\begin{equation}
f(z)=\frac{a_{0}}{2}+\sum_{n=1}^{\infty} (a_{n} \cos n z + b_{n} \sin n z)
\end{equation}

\begin{equation}
f(t)=\frac{a_{0}}{2}+\sum_{n=1}^{\infty}\left(a_{n} \cos \frac{n \pi}{L} t+b_{n} \sin \frac{n \pi}{L} t\right)
\end{equation}

\begin{equation}
\begin{aligned}
&a_{0}=\frac{1}{L} \int_{-L}^{L} f(t) \mathrm{d} t\\
&a_{n}=\frac{1}{L} \int_{-L}^{L} f(t) \cos \frac{n \pi}{L} t \mathrm{d} t \quad n=1,2 \ldots\\
&b_{n}=\frac{1}{L} \int_{-L}^{L} f(t) \sin \frac{n \pi}{L} t \mathrm{d} t \quad n=1,2 \ldots
\end{aligned}
\end{equation}

# Bibliography
